#                                              Numpy Tutorial 

**This is the Tut where i have covered and Learned all the concepts of the numpy maximum Which are useful for the Data Analysis
for the mathemeatical Concepts Learning **

In [2]:
#so Here We have Imported the Numpy Library here so that we can perform and use the functions which are there in numpy.
#Here numpy is the library so to use this library in an easy way we have given np alias numpy

import numpy as np

In [11]:
#Here We have Created an Numpy One Dimensional Arrray and printed that Array !!!!

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [7]:
#Now Let us Accesss the elements of the array
element1=a[0]
element2=a[1]
remaining_elements=a[2:]
print(element1)
print(element2)
print(remaining_elements)

#So here above we have created some variabes for each elements in the array and allocated the values in those variables for acessing the elements

1
2
[3 4]


In [13]:
#So this is the shape function which is used to find the dimensionality of the given numpy arrays 
# if the given array is of One Dimensional then the  shape of the arrays is --> The number of elements present in it
print(a.shape)

(4,)


In [14]:
#This will be printing the data type of the given array !!! 
print(a.dtype)

int32


# Creation Of the Numpy Arrays In Different Ways 

**1) Conversion From Other Python Structures**

In [15]:
#so here we have created the numpy one dimensional array using lists concept 
list_array=np.array([1,2,3,4,5])
print(list_array)

[1 2 3 4 5]


In [16]:
#so here we have created the numpy arrays using the tuple concepts 
tuple_array=np.array((1,5,6,7))
print(tuple_array)

[1 5 6 7]


**2)Intersinc numpy array creation objects**

In [20]:
#So here we will be creating the numpy arrays using some inbuilt functions like (arange ,ones,zeros)

# 1) Filling all the elements in the arrays with zeros using the numpy zeros 
b=np.zeros((4,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
#2) Filling all the elements in the arrays with ones using the numpy ones
c=np.ones((5,5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
#Using the arange Function to create the array 

#So here This is this is the range function which is used to create the range of values from a starting point to the ending point
#With a step difference between the consecutive numbers 
#Step difference means the difference between  i+1^th and i^th number 

# Syntax is : (starting_point,endingpoint,step_difference)
z=np.arange(0,5,1)
print(z)

[0 1 2 3 4]


In [31]:
#Here now we can also create an empty numpy array using the empty function in numpy !!!
emp=np.empty((4,4))
print(emp)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
#Linspace function is also there which is used to create the array but with in a range it creates a random equal setp difference
#elements and display them

x=np.linspace(1,7,10)
print(x)

#so it has created 10 elements between the elements 1 to 7 with equal step difference between elements 

[1.         1.66666667 2.33333333 3.         3.66666667 4.33333333
 5.         5.66666667 6.33333333 7.        ]


In [35]:
# Now Let us perform the reshape function and test its procedure

k=np.arange(1,9)
print(k)

[1 2 3 4 5 6 7 8]


In [42]:
#Here We are basically testing the reshape function 
#Note the product of the row and column should not be greater than the size of the elements 

k=k.reshape(4,2)

In [46]:
print(k)
print("")

# Printing the Numeber of the elements present in the array 
print("The number if elements are :",k.size)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]

The number if elements are : 8


In [48]:
#So here Ravel() is the function which is used to convert any dimensional array into proper one dimensional array 

k=k.ravel()
print(k)

[1 2 3 4 5 6 7 8]


**-->Axis Concept**

In [51]:
# so here we are creating the two dimensional list which has the 3x3 values can be known as 3 rows and 3 columns 
s=[[1,2,3],[4,5,6],[7,8,9]]

In [52]:
#Here we are passing the list into the arrays where that array later will be called as the 2D vector .....

arr=np.array(s)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
"""
Axis 0: Refers to rows. When performing operations along axis 0  we aggregate data column-wise.
Axis 1: Refers to columns. When performing operations along axis 1 we aggregate data row-wise.

Axis 0 aggregates across rows (affecting columns)
Axis 1 aggregates across columns (affecting rows)


"""

total=arr.sum(axis=0)
print(total)

[12 15 18]


In [61]:
tot=arr.sum(axis=1)
print(tot)

[ 6 15 24]


**Important Attributes**

In [62]:
#Here we re transposing a matrix which converts a row into the column as we have learned in the mathematics Transpose means inverseing

transpose=arr.T
print(transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [65]:
# Now lets is Create A falt To travers through the array 

# in simple words we have used flat and created an iterator which can traverse the array with the help of loop

flag=arr.flat

for item in flag:
    print(item)

1
2
3
4
5
6
7
8
9


In [68]:
# The usage of the ndim function for finding the dimensions 

print("The Dimensions of the arr array is :",arr.ndim)

The Dimensions of the arr array is : 2


In [69]:
# The dtype attribute which is used to find which data type has been stored in the array 
print(arr.dtype)

int32


In [70]:
#this is used to find the shape of the array which gives the number of rows and columns present in the array 
print(arr.shape)

(3, 3)


In [71]:
#This is used to find the size of the array that means number of elements 
print(arr.size)

9


**In Built Functions Used in the Numpy **

In [74]:
#This is the function called argmax which is used to find the maximum element in the array and return its index
maxi=arr.argmax()

print("The index of the maximum element in the array is :",maxi)

The index of the maximum element in the array is : 8


In [75]:
#This is the function called argmax which is used to find the minimum element in the array and return its index
minii=arr.argmin()

print("The index of the minimum element in the array is :",minii)

The index of the minimum element in the array is : 0


In [76]:
#This function is used to return the indices that would sort the array.
print(arr.argsort())

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [81]:
#Check this array for the below operations ....

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
"""
Using the Axis Concept in the Functions 
as we already know the axis concepts we are just combining them with the functions 

"""
print("The maximum elements in the  Columns are :",arr.argmax(axis=0))
print("The maximum elements in the rows are :",arr.argmax(axis=1))
print("The Minumum elements in the columns are :",arr.argmin(axis=0))
print("The Minumum elements in the rows are :",arr.argmin(axis=1))


The maximum elements in the  Columns are : [2 2 2]
The maximum elements in the rows are : [2 2 2]
The Minumum elements in the columns are : [0 0 0]
The Minumum elements in the rows are : [0 0 0]



**Mathematical Operations and functions on the array**

In [88]:
arr2=np.array([[5,6,7],[10,15,17],[1,6,4]])

In [94]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [89]:
print(arr2)

[[ 5  6  7]
 [10 15 17]
 [ 1  6  4]]


In [90]:
#This is used to perform the addition operation between the two arrays 
print(sum(arr,arr2))

[[17 21 25]
 [22 30 35]
 [13 21 22]]


In [91]:
#There are also some functions like multiplication subraction and division 
print(arr-arr2)

[[ -4  -4  -4]
 [ -6 -10 -11]
 [  6   2   5]]


In [92]:
print(arr*arr2)

[[  5  12  21]
 [ 40  75 102]
 [  7  48  36]]


In [93]:
print(arr/arr2)

[[0.2        0.33333333 0.42857143]
 [0.4        0.33333333 0.35294118]
 [7.         1.33333333 2.25      ]]


In [96]:
#This is the square root function which is present in the numpy arrays which is used to get the square root of the elements of
#the array 

print(np.sqrt(arr))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [99]:
"""
Some Stastical and other functions of the numpy arrays 

"""

print(np.where(arr>5))#This function returns the value greater than 5
print("No of non zero elements present in the array:",np.count_nonzero(arr))#Gives the non zero elements in the array 

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))
No of non zero elements present in the array: 9


In [102]:
#Some Stastical Functions used in numpy arrays

print("The median of the array is ",np.median(arr)) #median Function which calculates the median of the given array

The median of the array is  5.0


In [104]:
#corelation coefficent  function calculations

"""
This corelation coefficent can be defined as the relationship between two variables wich may be intended to be positive ,negative
and zero

"""

#The corelation coefficents of the array 
print(np.corrcoef(arr,arr2))

[[1.         1.         1.         1.         0.97072534 0.59603956]
 [1.         1.         1.         1.         0.97072534 0.59603956]
 [1.         1.         1.         1.         0.97072534 0.59603956]
 [1.         1.         1.         1.         0.97072534 0.59603956]
 [0.97072534 0.97072534 0.97072534 0.97072534 1.         0.77145428]
 [0.59603956 0.59603956 0.59603956 0.59603956 0.77145428 1.        ]]
